#pragma once

enum E_SVR_KIND_TYPE
{
    MAX_SVR_KIND_NONE = 150,
    SVR_KIND_CENTER,
    SVR_KIND_DB,
	SVR_KIND_FRIEND,
	SVR_KIND_GAME,
	SVR_KIND_GATE,
	SVR_KIND_HTTP,
	SVR_KIND_LOG,
	SVR_KIND_MAIL,
	SVR_KIND_MALL,
	SVR_KIND_SCENE,
	SVR_KIND_SCENECENTER,
	SVR_KIND_WORLD,
    MAX_SVR_KIND_TYPE
};
