// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/MsgSvrModule.proto

#include "server/MsgSvrModule.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace XrPb {
constexpr MsgSvrMod::MsgSvrMod(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct MsgSvrModDefaultTypeInternal {
  constexpr MsgSvrModDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~MsgSvrModDefaultTypeInternal() {}
  union {
    MsgSvrMod _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT MsgSvrModDefaultTypeInternal _MsgSvrMod_default_instance_;
}  // namespace XrPb
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_server_2fMsgSvrModule_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_server_2fMsgSvrModule_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_server_2fMsgSvrModule_2eproto = nullptr;

const uint32_t TableStruct_server_2fMsgSvrModule_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::XrPb::MsgSvrMod, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::XrPb::MsgSvrMod)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::XrPb::_MsgSvrMod_default_instance_),
};

const char descriptor_table_protodef_server_2fMsgSvrModule_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031server/MsgSvrModule.proto\022\004XrPb\"W\n\tMsg"
  "SvrMod\"J\n\005ModId\022\016\n\nNetSvrNone\020\000\022\017\n\013NetSv"
  "rBegin\020d\022\020\n\014NetSvrCommon\020e\022\016\n\tNetSvrEnd\020"
  "\377\001b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_server_2fMsgSvrModule_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_server_2fMsgSvrModule_2eproto = {
  false, false, 130, descriptor_table_protodef_server_2fMsgSvrModule_2eproto, "server/MsgSvrModule.proto", 
  &descriptor_table_server_2fMsgSvrModule_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_server_2fMsgSvrModule_2eproto::offsets,
  file_level_metadata_server_2fMsgSvrModule_2eproto, file_level_enum_descriptors_server_2fMsgSvrModule_2eproto, file_level_service_descriptors_server_2fMsgSvrModule_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_server_2fMsgSvrModule_2eproto_getter() {
  return &descriptor_table_server_2fMsgSvrModule_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_server_2fMsgSvrModule_2eproto(&descriptor_table_server_2fMsgSvrModule_2eproto);
namespace XrPb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgSvrMod_ModId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_server_2fMsgSvrModule_2eproto);
  return file_level_enum_descriptors_server_2fMsgSvrModule_2eproto[0];
}
bool MsgSvrMod_ModId_IsValid(int value) {
  switch (value) {
    case 0:
    case 100:
    case 101:
    case 255:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr MsgSvrMod_ModId MsgSvrMod::NetSvrNone;
constexpr MsgSvrMod_ModId MsgSvrMod::NetSvrBegin;
constexpr MsgSvrMod_ModId MsgSvrMod::NetSvrCommon;
constexpr MsgSvrMod_ModId MsgSvrMod::NetSvrEnd;
constexpr MsgSvrMod_ModId MsgSvrMod::ModId_MIN;
constexpr MsgSvrMod_ModId MsgSvrMod::ModId_MAX;
constexpr int MsgSvrMod::ModId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class MsgSvrMod::_Internal {
 public:
};

MsgSvrMod::MsgSvrMod(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:XrPb.MsgSvrMod)
}
MsgSvrMod::MsgSvrMod(const MsgSvrMod& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:XrPb.MsgSvrMod)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgSvrMod::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgSvrMod::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata MsgSvrMod::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_server_2fMsgSvrModule_2eproto_getter, &descriptor_table_server_2fMsgSvrModule_2eproto_once,
      file_level_metadata_server_2fMsgSvrModule_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace XrPb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::XrPb::MsgSvrMod* Arena::CreateMaybeMessage< ::XrPb::MsgSvrMod >(Arena* arena) {
  return Arena::CreateMessageInternal< ::XrPb::MsgSvrMod >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
